#!/usr/bin/env bash
# Keep every published copy of the site in step with the data and with each
# other.
#
# WHY TWO COPIES EXIST
#   GitHub Pages for this repository is configured (by whoever set it up, via
#   the repo settings) to publish from the repository ROOT, and that setting
#   cannot be changed with the available token. The canonical, reviewable site
#   therefore lives in docs/, and root-level copies are generated from it.
#
#   No path rewriting is needed: app.js resolves its data files by trying the
#   root layout first and falling back to the docs layout (see loadFirst()).
#
# tests/test_pipeline.py::TestSiteDataContract asserts these copies stay
# byte-identical, so forgetting to run this fails the test suite rather than
# silently shipping a stale page.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "$root/docs/data"

# 1. data artefacts -> docs/data (docs layout)
cp "$root/data/discrepancies.json"                  "$root/docs/data/"
cp "$root/data/evidence/score_integrity_study.json" "$root/docs/data/"
cp "$root/data/market_sensitivity_2025_2026.json"   "$root/docs/data/"

# 1a. the source-movement study -> docs/data (optional: it is regenerated by
#     `run.py churn`, and the site renders an explicit "no study published"
#     state rather than breaking when a fresh fork has none)
if [ -f "$root/data/evidence/upstream_churn_study.json" ]; then
  cp "$root/data/evidence/upstream_churn_study.json" "$root/docs/data/"
fi

# 1c. the subscribable Atom feeds -> docs/data (optional, generated by
#     `run.py atom`). Relative <link rel="alternate"> hrefs in index.html resolve
#     in both published layouts, so one HTML file works in both places.
if [ -f "$root/data/corrections.atom" ]; then
  cp "$root/data/corrections.atom" "$root/docs/data/"
fi

# 1b. the live detection feed, the monitor self-assessment, the attempt ledger
#     and the delivery receipts -> docs/data/alerts/ (all optional: a fresh fork
#     has none yet, and the site renders "no runs recorded" / "no attempt
#     recorded" / an UNKNOWN assessment rather than breaking)
mkdir -p "$root/docs/data/alerts"
for f in feed.json feed.atom health.json attempts.json deliveries.json; do
  if [ -f "$root/data/alerts/$f" ]; then
    cp "$root/data/alerts/$f" "$root/docs/data/alerts/"
  fi
done

# 2. canonical site assets -> repository root (root layout)
for f in index.html app.js styles.css; do
  cp "$root/docs/$f" "$root/$f"
done
cp "$root/docs/.nojekyll" "$root/.nojekyll"

echo "synced data artefacts (database, studies, live feed, health, deliveries, Atom feeds) -> docs/data/"
echo "synced 4 site assets (index.html, app.js, styles.css, .nojekyll) -> repo root"
